/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author LENOVO
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        LbSpider1 = new javax.swing.JLabel();
        LbSpider2 = new javax.swing.JLabel();
        LbSpider3 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        BtnSpider1 = new javax.swing.JButton();
        BtnSpider2 = new javax.swing.JButton();
        BtnSpider3 = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        imagePanel.setLayout(new java.awt.CardLayout());

        LbSpider1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSpider1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/spiderman-1.jpg"))); // NOI18N
        LbSpider1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LbSpider1.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(LbSpider1, "0");

        LbSpider2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSpider2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/spiderman-2.jpg"))); // NOI18N
        LbSpider2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(LbSpider2, "1");

        LbSpider3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSpider3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/spiderman-3.jpg"))); // NOI18N
        LbSpider3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagePanel.add(LbSpider3, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        BtnSpider1.setText("Spider-Man 1");
        BtnSpider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSpider1ActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnSpider1);

        BtnSpider2.setText("Spider-Man 2");
        BtnSpider2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSpider2ActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnSpider2);

        BtnSpider3.setText("Spider-Man 3");
        BtnSpider3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSpider3ActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnSpider3);

        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        buttonPanel.add(BtnExit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSpider2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSpider2ActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"1");
    }//GEN-LAST:event_BtnSpider2ActionPerformed

    private void BtnSpider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSpider1ActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"0");
    }//GEN-LAST:event_BtnSpider1ActionPerformed

    private void BtnSpider3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSpider3ActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel,"2");
    }//GEN-LAST:event_BtnSpider3ActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
                GraphicsDevice device = 
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnSpider1;
    private javax.swing.JButton BtnSpider2;
    private javax.swing.JButton BtnSpider3;
    private javax.swing.JLabel LbSpider1;
    private javax.swing.JLabel LbSpider2;
    private javax.swing.JLabel LbSpider3;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    // End of variables declaration//GEN-END:variables
}
